### ISSUE TITLE
Is it possible to use RecyclerViewItems that have no container layout?

### ISSUE THREAD

**Issue by rasfra** [agoda-com/Kakao#99] opened 2018-04-25 15:35 UTC
#### Steps to reproduce:

  1. Create a RecycleView with a layout containing only a single element
```
<layout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools">
    <data />
    <SomeView android:id="@+id/some_id"/>
</layout>
```
  2. Setup a KRecyclerView with an item containing only someView

```
class MyScreen : Screen<MyScreen>() {
    val recyclerView= KRecyclerView({ withId(R.id.myRV) }, (::Item) })
    class Item(parent: Matcher<View>) : KRecyclerItem<Item>(parent) {
        val someView= KView(parent) { withId(R.id.some_id) }
    }
}

```
  3. Try to use it

```
MyScreen(){
    recyclerView {
        firstChild<MyScreen.Item> {
            someView { doStuff()}
        }
    }
}
```

  
#### Observed Results:

android.support.test.espresso.NoMatchingViewException: No views in hierarchy found matching: (is descendant of a: (view holder at 0 position of recycler view: (with id: myapp:id/myrecyclerview)) and with id: 2131363029)

Layout contains a recyclerview with 9 direct children of SomeView Type with matching Ids. I think the problem is that it assumes that the item i'm looking for is a grandchild of the recycler view rather than a child. If I wrap someView in a LinearLayout, things works as expected

#### Expected Results:

 I expected being able to use recycler views with only direct children. Am I doing it wrong or is this a bug? Is it possible to setup the screen so that someView IS the KRecyclerItem?

I hope the quality of this was enough, I'm new with both kotlin and android.

**Comment by Alviere** [comment] 2018-04-26 05:46
Hello there!
Actually, the `parent` that you are retrieving here is actually a matcher to the holder top view (container) itself. So, if you want to do something with it, use is as matcher of the view, not parent.
Here's your reworked sample:
```
class MyScreen : Screen<MyScreen>() {
    val recyclerView= KRecyclerView({ withId(R.id.myRV) }, (::Item) })
    class Item(parent: Matcher<View>) : KRecyclerItem<Item>(parent) {
        val self = KView { withMatcher(parent) }
    }
}
```
Hope this helps. Cheers!

**Comment by rasmusfranke** [comment] 2018-04-26 05:57
Ahh that makes sense, thanks a lot!

**Comment by Alviere** [comment] 2018-04-26 05:59
Glad to hear that! Then the issue is solved, closing it.
Happy testing!

**Closed by Alviere** 2018-04-26 05:59 UTC
Labels: question

**Comment by sebastienrouif** [comment] 2019-09-27 09:05
@Unlimity I ran into the same problem, would it be worth adding an example in the sample, I have two places in mind :
 - in the current recyclerView example (but it might make it complex to approach)
 - as new recyclerView example
I'm happy to submit a PR

**Comment by Unlimity** [comment] 2019-09-27 09:10
@sebastienrouif thanks for reaching out!
If you're willing to submit an example, I think it's better to provide such use case as a separate example since this is not a common use case.
