### ISSUE TITLE
pressImeAction fails because view "is a root view"

### ISSUE THREAD

**Issue by JolandaVerhoef** [agoda-com/Kakao#74] opened 2018-01-26 12:21 UTC
The accompanying `ViewActions.pressImeActionButton()` runs correctly. 

I created a branch to demonstrate the issue, see https://github.com/JolandaVerhoef/Kakao/commit/77c192a24575be861aba7ed921832824904a651a
  
#### Observed Results:

  * Failing test when trying to run `pressImeAction`
  
#### Expected Results:

  * I would expect it to run correctly

**Comment by Alviere** [comment] 2018-01-29 05:29
Hello there. Thank you for your contribution!
I've found the root cause, and the fix is ready at #75 and will be included in upcoming minor release.
Take care!

**Comment by Alviere** [comment] 2018-01-30 05:30
Fixed. Closing this issue.
Thanks again for pointing that bug out, @JolandaVerhoef !

**Closed by Alviere** 2018-01-30 05:30 UTC
Labels: bug
