### ISSUE TITLE
WithIndex is not working properly

### ISSUE THREAD

**Issue by michalkierasinski** [agoda-com/Kakao#90] opened 2018-03-20 13:04 UTC
#### Steps to reproduce:

  1. Create a layout with views with the same id
  2. Write a simple test using withIndex method
  3. Execute test

#### Observed Results:

Error message - Espresso could not found a matching view.
  
`android.support.test.espresso.NoMatchingViewException: No views in hierarchy found matching: (0th view with: (with id: com.agoda.sample:id/input_layout))`
#### Expected Results:

It should work.
  
#### Relevant Code:
[Sample project with error](https://github.com/agoda-com/Kakao/files/1829363/withIndexSample.zip)

**Comment by Alviere** [comment] 2018-03-21 04:14
Thank you for the report!
We will investigate it in the coming days.

**Comment by Alviere** [comment] 2018-03-22 04:21
I found the issue in your sample.
The problem is that `withIndex` matcher is one-time use only. After it matches item, it is no longer usable.
You can make it dynamic though. Modify your `InputScreen` class in attached sample:
```
class InputScreen : Screen<InputScreen>() {
    fun inputLayout(lambda: KEditText.() -> Unit) = KEditText { withIndex(0, { withId(R.id.input_layout) }) }.invoke(lambda)
}
```
Hope this will help you.

**Comment by michalkierasinski** [comment] 2018-03-22 08:00
Your solution does not work. I get the same error: `No views in hierarchy found matching: (1th view with: (with id: com.agoda.sample:id/input_layout))`. 

Every invocation executes the same `withIndex` matcher.

**Comment by michalkierasinski** [comment] 2018-03-22 08:14
Ok, now it is working. Thanks for the help.

**Comment by Alviere** [comment] 2018-03-22 08:37
You're welcome. Closing this issue then.

**Closed by Alviere** 2018-03-22 08:37 UTC
Labels: question
